classdef carousel_parameters_class_control
    properties
        names_components
        ports_working
        cp_gas_components
        Rm_clean
        Rm_array
        wg_end
        time_vector
        control_interval
        V_slurry
        Q
        error_t_rot
        filtration_sampling_time
        number_components
        number_volatile_components
        Rm_vect
        visc_liq_coeff 
        MW_components
        cp
        rho_liq_components
        c_inlet
        Di_liq
        cp_liq_components
        vl_crit
        h_M
        vl_eq
        latent_heat
        coeff_antoine
        station_diameter
        Rm
        rho_sol
        zeta
        visc_gas_phase
        surf_t
        lambda
        k0
        gamma
        A
        E
        m0
        m1
        m2
        m3
        alpha
        k
        a_V
        k_air
        MW_air
        cp_air
        cp_s
        number_nodes_deliq
        number_nodes_filt
        number_nodes_washing
        number_nodes_drying
        time_step_deliq
        time_step_filt
        time_step_drying
        min_length_discr
        t_rot
        W
        dP       
        drying_sampling_time
        dP_drying
        Tinlet_drying
        L_cake
        Pb
        V_liquid_pores
        m_dry_cake
        dP_media_vacuum
        S_inf
        number_nodes
        nodes_list
        step_grid_drying
        nodes_drying
        dPgdz
        ug
        Pprofile
        cp_l
        rho_l
        repLatHeat
        repRhoLComp
        h_T
        epsL_non_vol
        step_grid_deliq
        nodes_deliq
        Pgin
        Pgout
        Pg
        scaling
        step_grid_washing
        nodes_washing
        lambda_ads
        visc_liq
        x
        CSD
        x_perc
        CSD_perc
        wash_solvent_mass_fr
        k_ads
        n_cycle_cip
    end 
    methods 
        function output=visc_liq_components(obj,T)  % Liquid viscosity [Pa s] - T in [K] Yaw
            output=10.^(obj.visc_liq_coeff(:,1)+obj.visc_liq_coeff(:,2)/T+...
                obj.visc_liq_coeff(:,3)*T+obj.visc_liq_coeff(:,4)*T^2)*1e-3;  
        end            
        function output=N_cap_CSD(obj,x,rho_liq,E,dP,L_cake) % capillary number - Tarleton and Wakeman, 2007
            output=(E^3*(x).^2*(rho_liq*9.81.*L_cake+dP))/((1-E)^2*L_cake.*obj.surf_t);
        end
        function output=pb_CSD(obj,x,E) % threshold pressure - Tarleton and Wakeman, 2007
            output=4.6*(1-E)*obj.surf_t./(E*x);
        end
    end
end
